#!/bin/sh
set -e

echo "Postrm argument: $1"

config_dir="/etc/purge-backups"

case "$1" in
    remove|upgrade|deconfigure)
        # Remove /etc/purge-backups directory if it is empty
        if [ -d "$config_dir" ] && [ -z "$(ls -A $config_dir)" ]; then
          rmdir $config_dir
        fi

        # Remove the cronjob from the current user's crontab
        (crontab -l | grep -v "/usr/share/purge-backups/purge-backups-scheduler" ) | crontab -

        ;;
    *)
        # Do nothing on other actions
        exit 0
        ;;
esac

# Continue with package removal
exit 0
