#!/bin/bash

set -e

case "$1" in
    configure)
        # Check if the cronjob is already present
        if ! crontab -l | grep -q "/usr/share/purge-backups/purge-backups-scheduler"; then
            # Add the cronjob to the current user's crontab
            (crontab -l 2>/dev/null || true; echo "0 0 * * * /usr/share/purge-backups/purge-backups-scheduler # Part of purge-backups package. DO NOT CHANGE!") | crontab -

            # Enable the cron service
            update-rc.d cron enable || true

            # Restart the cron service (optional)
            service cron restart || true
        else
            echo "Cronjob already exists. Skipping addition."
        fi
        ;;
    *)
        # Do nothing on other actions
        exit 0
        ;;
esac

exit 0
