#!/bin/bash

set -e

case "$1" in
    configure)
        # Add the cronjob to the current user's crontab

        (crontab -l ; echo "0 0 * * * /usr/share/purge-backups/purge-backups-scheduler") | crontab - | at now + 1 minute
        ;;
    *)
        # Do nothing on other actions
        exit 0
        ;;
esac

exit 0
