#!/bin/sh
set -e

echo "Preinst argument: $1"

config_dir="/etc/purge-backups"

if [ "$1" = "install" ]; then

  # Create /etc/purge-backups directory if it doesn't already exist
  if [ ! -d "$config_dir" ]; then
    mkdir -p $config_dir
    chown root:root $config_dir
    chmod 755 $config_dir
  fi
fi

# Continue with package installation
exit 0
