#!/bin/bash

# Set the default configuration directory
CONFIG_DIR="/etc/purge-backups"

# Default retention periods
DEFAULT_DAILY="7d"
DEFAULT_WEEKLY="4w"
DEFAULT_MONTHLY="12m"
DEFAULT_YEARLY="3y"

# Print usage message
usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

  -h, --help          Print this help message
  -c, --config-dir    Set the configuration directory (default: $CONFIG_DIR)
  -d, --dry-run       Perform a dry run without executing the purge-backups command
EOF
}

# Parse command line options
while [[ "$#" -gt 0 ]]; do
  case $1 in
    -h|--help)
      # Print help and exit
      usage
      exit 0
      ;;
    -c|--config-dir)
      # Set the configuration directory
      if [[ "$2" == /* ]]; then
        # Absolute path
        CONFIG_DIR="$2"
      else
        # Relative path
        CONFIG_DIR="$PWD/$2"
      fi
      shift
      ;;
    -d|--dry-run)
      # Perform a dry run
      DRY_RUN=1
      ;;
    *)
      # Invalid option
      echo "Invalid option: $1" >&2
      usage
      exit 1
      ;;
  esac
  shift
done

# Loop through all .cfg files in the config directory
for file in "$CONFIG_DIR"/*.cfg; do
  # Source the file to set the variables
  # shellcheck disable=SC1090
  source "$file"

  # Set default values for retention periods if they are not set in the .cfg file
  DAILY=${DAILY:-$DEFAULT_DAILY}
  WEEKLY=${WEEKLY:-$DEFAULT_WEEKLY}
  MONTHLY=${MONTHLY:-$DEFAULT_MONTHLY}
  YEARLY=${YEARLY:-$DEFAULT_YEARLY}

  # Perform a dry run if specified
  if [ "$DRY_RUN" ]; then
    echo "purge-backups -p \"$BACKUP_PATH\" -x \"$BACKUP_PREFIX\" -d \"$DAILY\" -w \"$WEEKLY\" -m \"$MONTHLY\" -y \"$YEARLY\""
  else
    # Call the purge-backups command with the extracted parameters
    purge-backups -p "$BACKUP_PATH" -x "$BACKUP_PREFIX" -d "$DAILY" -w "$WEEKLY" -m "$MONTHLY" -y "$YEARLY"
  fi
done
